apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployement
  labels:
    app: nginx-deployement
spec:

  # Creating two Pods
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: nginx-app
        image: nknagaraj/nginx:1.16.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8090