# Secret file for the private repository
apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
  namespaces: canart_deployement
data:
  .dockerconfigjson: base64-encoded-contents-of-.docker/config.json-file
type: kubernetes.io/dockerconfigjson
