apiVersion: v1
kind: Service
metadata:
  name: python-svc-stable
  namespace: python-app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: python-app
    version: blue
    # version: green
  type: LoadBalancer